language: python

python:
  - "2.7"
  - "3.5"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python -m doctest tsenum/__init__.py
  - python setup.py bdist_egg
  - python setup.py bdist_wininst
  - python setup.py sdist
