language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .

script:
  - python setup.py test 
  - python setup.py bdist_egg
  - python setup.py bdist_wininst
  - python setup.py sdist
