name: Lint

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: "docker.io/library/python:latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run checks
        run: |
          hatch run dev:style tsenum
