name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/tsenum
    permissions:
      # IMPORTANT: required for trusted publishing
      # See https://github.com/marketplace/actions/pypi-publish#usage
      id-token: write  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install hatch
        run: pip install hatch

      - name: Get version nubmer
        id: vars
        run: echo "version=$(hatch version)" >> $GITHUB_OUTPUT

      - name: Create release on GitHub
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "${{ steps.vars.outputs.version }}"
          release_name: "Release v${{ steps.vars.outputs.version }}"
          draft: false
          prerelease: false

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
