name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    container: "docker.io/library/python:latest"
    environment:
      name: release
      url: https://pypi.org/p/tsenum
    permissions:
      # IMPORTANT: required for trusted publishing
      # See https://github.com/marketplace/actions/pypi-publish#usage
      id-token: write  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install hatch
        run: pip install hatch

      - name: Build
        run: hatch build

      - name: Get version nubmer
        id: vars
        run: echo "version=$(hatch version)" >> $GITHUB_OUTPUT

      - name: Create release on GitHub
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "v${{ steps.vars.outputs.version }}"
          release_name: "Release v${{ steps.vars.outputs.version }}"
          draft: false
          prerelease: false

      - name: Append wheel on release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
          asset_name: "tsenum-${{ steps.vars.outputs.version }}-py3-none-any.whl"
          asset_path: "dist/tsenum-${{ steps.vars.outputs.version }}-py3-none-any.whl"
          asset_content_type: application/zip

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
